services:
  spring-config-server:
    image: vis2022/sample/spring-config-server:0.0.4-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8888:8888"
    networks:
      - my-network
      
  limits-service:
    image: vis2022/sample/limits-service:0.0.3-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - spring-config-server
    environment:
      SPRING.CONFIG.IMPORT: optional:configserver:http://spring-config-server:8888
      SPRING.CLOUD.CONFIG.NAME: microservice-details
      SPRING.PROFILES.ACTIVE: qa
      SPRING.CLOUD.CONFIG.PROFILE: qa
  
  currency-exchange:
    image: vis2022/sample/currency-exchange-service:0.0.2-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - my-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.SLEUTH.SAMPLER.PROBABILITY: 1.0
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      
  currency-conversion:
    image: vis2022/sample/currency-conversion-service:0.0.2-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - my-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.SLEUTH.SAMPLER.PROBABILITY: 1.0
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  api-gateway:
    image: vis2022/sample/api-gateway:0.0.2-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - my-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.SLEUTH.SAMPLER.PROBABILITY: 1.0
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  naming-server:
    image: vis2022/sample/naming-server:0.0.2-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - my-network
      
  zipkin-server:
    image: openzipkin/zipkin
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - my-network
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    restart: always #Restart if there is a problem starting up

  rabbitmq:
    image: rabbitmq:3.9-management
    mem_limit: 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network


networks:
  my-network: